### ISSUE TITLE
The website（The frbtheorycat. website is not accessible） is not accessible

### ISSUE THREAD

**Issue by kongjunZhang** [KshitijAggarwal/FRB-journal-club#1]
The  website（The frbtheorycat. website is not accessible） is not accessible

**Comment by devanshkv** [comment]
You should contact the authors of the paper [A Living Theory Catalogue for Fast Radio Bursts](https://arxiv.org/abs/1810.05836).

**Comment by kongjunZhang** [comment]
thanks
